/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface": "#e3e0f4",
        "on-surface-variant": "#ccc3d7",
        "on-primary-fixed-variant": "#5b0dbe",
        "on-primary-fixed": "#260059",
        "primary-fixed": "#ebdcff",
        "surface": "#12121f",
        "primary": "#d4bbff",
        "surface-variant": "#343342",
        "on-error-container": "#ffdad6",
        "on-secondary-container": "#d6a9ff",
        "on-tertiary-fixed": "#2d1600",
        "inverse-on-surface": "#2f2f3d",
        "outline-variant": "#4a4454",
        "surface-bright": "#383847",
        "on-background": "#e3e0f4",
        "inverse-surface": "#e3e0f4",
        "on-tertiary-fixed-variant": "#6a3c00",
        "background": "#12121f",
        "on-secondary-fixed-variant": "#6900b3",
        "surface-container-highest": "#343342",
        "surface-tint": "#d4bbff",
        "on-secondary-fixed": "#2c0051",
        "secondary-fixed-dim": "#ddb7ff",
        "primary-fixed-dim": "#d4bbff",
        "on-primary": "#40008c",
        "outline": "#968da0",
        "tertiary-fixed-dim": "#ffb871",
        "error": "#ffb4ab",
        "on-secondary": "#490080",
        "tertiary": "#ffb871",
        "on-error": "#690005",
        "primary-container": "#8247e5",
        "secondary-container": "#6f00be",
        "tertiary-fixed": "#ffdcbe",
        "on-tertiary": "#4a2800",
        "error-container": "#93000a",
        "tertiary-container": "#9e5c00",
        "surface-container-low": "#1a1a28",
        "surface-dim": "#12121f",
        "secondary-fixed": "#f0dbff",
        "secondary": "#ddb7ff",
        "inverse-primary": "#7436d6",
        "on-tertiary-container": "#ffebdb",
        "on-primary-container": "#f5eaff",
        "surface-container-high": "#292937",
        "surface-container": "#1e1e2c",
        "surface-container-lowest": "#0d0d1a",
        "success": "#10B981",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};
